webapp/Library/process_bar/__init__.py
#encoding:utf-8
import sys
class ShowProcess():
    """
    显示处理进度的类
    调用该类相关函数即可实现处理进度的显示
    """
    i = 0 # 当前的处理进度
    max_steps = 0 # 总共需要处理的次数
    max_arrow = 50 #进度条的长度

    # 初始化函数，需要知道总共的处理次数
    def __init__(self, max_steps):
        self.max_steps = max_steps
        self.i = 0

    # 显示函数，根据当前的处理进度i显示进度
    # 效果为[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00%
    def show_process(self, i=None):
        if i is not None:
            self.i = i
        else:
            self.i += 1
        num_arrow = int(self.i * self.max_arrow / self.max_steps) #计算显示多少个'>'
        num_line = self.max_arrow - num_arrow #计算显示多少个'-'
        percent = self.i * 100.0 / self.max_steps #计算完成进度，格式为xx.xx%
        process_bar = '[' + '>' * num_arrow + '-' * num_line + ']'\
                      + '%.2f' % percent + '%' #带输出的字符串，'\r'表示不换行回到最左边
         #这两句打印字符到终端
        sys.stdout.write('\r')
        sys.stdout.write(process_bar)

    def close(self, words='done'):
        print ''
        print words
        self.i = 0

webapp/admin/__init__.py
# -*- coding: utf-8 -*-：
from flask_admin import Admin
from views import *
from webapp.models import *
from flask.ext.admin import AdminIndexView, expose

# def create_admin(app=None):
#     # admin = Admin(app)
#     admin = Admin(app,name="FIAS", index_view=MyIndexView(), base_template='admin/my_master.html')
#     if(UserView.is_accessible):
#         admin.add_view(UserView(db.session, name=u'用户列表'))
#     if(User_Role_View.is_accessible):
#         admin.add_view(User_Role_View(db.session, name=u'用户权限'))

webapp/controllers/restfulapi.py
# encoding=utf-8
from flask import Blueprint, redirect, render_template, url_for, request, session, make_response, jsonify, flash
from webapp.models import *
import MySQLdb, time, re
from sqlalchemy import create_engine, or_, func, desc, distinct  # me func用于计数,desc用于逆序找max值
from sqlalchemy.orm import sessionmaker  # me
from flask_login import current_user
import string
from collections import Counter
import tushare as ts
import gc
import pandas as pd
from datetime import datetime
from datetime import timedelta
from  webapp.stratlib import *
# from webapp.Library.wind_mysql.get_company_list import *
import time as Time
api_blueprint = Blueprint(
    'restfulapi',
    __name__,
    url_prefix='/api'
)


@api_blueprint.route("/admin/", methods=('GET', 'POST'))
def admin():
    stockcode = request.args.get('code')
    results = users_roles.query.all()
    name_list = []
    permission_list = []
    for result in results:
        name_list.append(result.user_name)
        permission_list.append(result.permissions)
    data = {
        'name_list': name_list,
        "permission_list": permission_list
    }
    return jsonify(data)


# 购买数据
@api_blueprint.route('/ buy_data', methods=['GET', 'POST'])
def buy_data():
    username = request.args.get('username')

    money = user_money.query.filter_by(user_name=username).first_or_404().user_money
    member_type = member_information.query.filter_by(user_name=username).first_or_404().member_type
    time = member_information.query.filter_by(user_name=username).first_or_404().member_expiration_date
    results = {
        'user_money': money,
        'member_type': member_type,

    }
    return jsonify(results)


# 账户余额操作，充值，花费
@api_blueprint.route('/change_money', methods=['GET', 'POST'])
def change_money():
    username = current_user.username
    action =  request.args.get('action')
    count = request.args.get('count')

    if(action == 'sub'):
        result = user_money.query.filter_by(user_name=username).first_or_404()
        result.user_money = result.user_money - int(count)
        db.session.commit()
    else:
        result = user_money.query.filter_by(user_name=username).first_or_404()
        result.user_money = result.user_money + int(count)
        db.session.commit()
    results = {
        'action':action,
        'count':count,

    }
    return jsonify(results)






# 数据库查询api 用于Ajax数据返回 json格式数据
@api_blueprint.route("/finance_data/", methods=('GET', 'POST'))

def finance_data():
    stockcode = request.args.get('stockcode')
    starttime = request.args.get('starttime')
    endtime = request.args.get('endtime')
    indexes = request.args.getlist('indexes[]')
    filters = {
        finance_basics.trade_code == stockcode,
        finance_basics.the_year >= starttime,
        finance_basics.the_year <= endtime,
    }
    results = finance_basics.query.filter(*filters).all()
    result1 = finance_basics.query.filter_by(trade_code=stockcode).first_or_404()

    data = {}
    year_list = []
    data['the_name'] = result1.sec_name
    for index in indexes:
        exec (index + "_list=[]")

    for result in results:
        year_list.append(result.the_year)
        for index in indexes:
            if eval("result." + index) is None:
                exec (index + "_list.append(result." + index + ")")
            else:
                exec (index + "_list.append(float(result." + index + "))")

    data['stock_code'] = stockcode
    data['the_year'] = year_list
    data['indexes'] = indexes
    for index in indexes:
        exec ("data['" + index + "']=" + index + "_list")
    return jsonify(data)

@api_blueprint.route("/code_wind/", methods=('GET', 'POST'))
def code_wind():
    code_list = request.args.getlist('codelist[]')

    data = {}

    data['codelist'] = code_list

    return jsonify(data)


@api_blueprint.route('/change_permission', methods=('GET', 'POST'))
def change_permission():
    name = request.form.get('name')
    permission = request.form.get('permission')

    old_users_roles = users_roles.query.filter_by(user_name=name).first()
    db.session.delete(old_users_roles)
    db.session.commit()

    n_users_roles = users_roles(user_name=name)
    n_users_roles.permissions = permission
    db.session.add(n_users_roles)
    db.session.commit()
    data = {
        'name': name,
        'permission': permission
    }
    return jsonify(data)


@api_blueprint.route('/get_ajax_compare', methods=('GET', 'POST'))
def get_ajax_compare():
    code = request.form.get('code')
    date = request.form.getlist('date[]')
    indexes = request.form.getlist('index[]')
    the_year_start = int(date[0][0:4] + '1231')
    the_year_end = int(date[1][0:4] + '1231')
    data = {}
    test = {}
    year_list = []
    year_list1 = []
    the_name_list = []
    the_year = the_year_end
    while the_year >= the_year_start:
        year_list.append(the_year)
        year_list1.append(the_year / 10000)
        the_year = the_year - 10000
    result1 = finance_basics.query.filter_by(trade_code=code).first_or_404()
    data['the_name'] = result1.sec_name
    for index in indexes:
        results = []
        for year in year_list:
            if index == 'ebit_rate':
                result = finance_basics_add.query.filter_by(trade_code=code, the_year=year).first_or_404()
                if eval('result.' + index) is None:
                    results.append('..')
                else:
                    results.append(str(eval('result.' + index)))
            else:
                result = finance_basics.query.filter_by(trade_code=code, the_year=year).first_or_404()
                if eval('result.' + index) is None:
                    results.append('..')
                else:
                    results.append(str(eval('result.' + index)))
        data[index] = results
    data['the_code'] = code
    data['indexs'] = indexes
    data['the_year_list'] = year_list1

    return jsonify(data)


@api_blueprint.route('/get_ajax', methods=('GET', 'POST'))
def get_ajax():
    code = request.form.get('code')
    date = request.form.getlist('date[]')
    indexes = request.form.getlist('selected[]')

    the_year_start = int(date[0][0:4] + '1231')
    the_year_end = int(date[1][0:4] + '1231')

    data = {}
    year_list = []
    year_list1 = []
    the_year = the_year_end
    while the_year >= the_year_start:
        year_list.append(the_year)
        year_list1.append(the_year / 10000)
        the_year = the_year - 10000

    result1 = finance_basics.query.filter_by(trade_code=code).first_or_404()
    data['the_name'] = result1.sec_name

    for index in indexes:
        results = []
        for year in year_list:
            if index == 'ebit_rate':
                result = finance_basics_add.query.filter_by(trade_code=code, the_year=year).first_or_404()
                if eval('result.' + index) is None:
                    results.append('..')
                else:
                    results.append(str(eval('result.' + index)))
            else:
                result = finance_basics.query.filter_by(trade_code=code, the_year=year).first_or_404()
                if eval('result.' + index) is None:
                    results.append(0)
                else:
                    results.append(str(eval('result.' + index)))

        data[index] = results
    data['indexs'] = indexes
    data['the_code'] = code
    data['the_year_list'] = year_list1
    return jsonify(data)


@api_blueprint.route('/iscode', methods=('GET', 'POST'))
def iscode():
    data = {}
    code = request.form.get('code')
    result1 = finance_basics.query.filter_by(trade_code=code).first()
    if (result1):
        data['the_name'] = result1.sec_name
    else:
        data['the_name'] = 'false'
    data['the_code'] = code
    return jsonify(data)


@api_blueprint.route("/finance_data_new/", methods=('GET', 'POST'))
def finance_data_new():
    stockcode = request.args.getlist('stockcode[]')
    starttime = request.args.get('starttime')
    endtime = request.args.get('endtime')
    indexes = request.args.getlist('indexes[]')
    data = {}
    year_list = []
    the_year_start = int(starttime[0:4])
    the_year_end = int(endtime[0:4])
    the_year = the_year_end
    while the_year >= the_year_start:
        year_list.append(the_year)
        # year_list1.append(the_year / 10000)
        the_year = the_year - 1
    for index in indexes:
        exec (index + "_list=[]")
    data['the_name'] = []
    for code in stockcode:
        filters = {
            finance_basics.trade_code == code,
            finance_basics.the_year >= starttime,
            finance_basics.the_year <= endtime,
        }
        results = finance_basics.query.filter(*filters).all()
        result1 = finance_basics.query.filter_by(trade_code=code).first_or_404()
        data['the_name'].append(result1.sec_name)
        for result in results:
            # year_list.append(result.the_year)
            for index in indexes:
                if eval("result." + index) is None:
                    exec (index + "_list.append(result." + index + ")")
                else:
                    exec (index + "_list.append(float(result." + index + "))")

    data['stock_code'] = stockcode
    data['the_year'] = year_list
    data['indexes'] = indexes
    for index in indexes:
        exec ("data['" + index + "']=" + index + "_list")
    return jsonify(data)


@api_blueprint.route("/invest_data_new/", methods=('GET', 'POST'))
def invest_data_new():
    stockcode = request.args.getlist('stockcode[]')
    starttime = request.args.get('starttime')
    endtime = request.args.get('endtime')
    indexes = request.args.getlist('indexes[]')
    data = {}
    year_list = []
    the_year_start = int(starttime[0:4])
    the_year_end = int(endtime[0:4])
    the_year = the_year_end
    while the_year >= the_year_start:
        year_list.append(the_year)
        # year_list1.append(the_year / 10000)
        the_year = the_year - 1
    for index in indexes:

webapp/controllers/stock_solo.py
#coding=utf-8
from flask import Blueprint,redirect,render_template,url_for,request, jsonify,session
from os import path
from webapp.models import *
from webapp.forms import CodeForm
from flask_login import login_required,current_user
from webapp.extensions import finance_analyst_permission # 这个就是经济师权限
from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
import MySQLdb,time,re #re用于判断是否含中文
import numpy as np
import restfulapi
from webapp.decorators import admin_required,permission_required

#用于判断是否含中文
zhPattern = re.compile(u'[\u4e00-\u9fa5]+')
stocksolo_blueprint = Blueprint(
    'stock_solo',
    __name__,
    template_folder=path.join(path.pardir,'templates','stock_solo'),
    url_prefix="/stock_solo"
)
@stocksolo_blueprint.route('/',methods=('GET','POST'))
@stocksolo_blueprint.route('/<string:data>',methods=('GET','POST'))
def basic(data=""):
    if data=="":
        if session.has_key('stockcode'):
            data = session['stockcode']
        else:
            data = '000001'
    if (request.method == 'POST'):
        stockcode=request.form.get("stockcode","000001")
        session['stockcode'] = stockcode
        return redirect(url_for('stock_solo.basic', current_user=current_user, data=stockcode))
    match = zhPattern.search(data)
    if match:
        stock = stock_basics.query.filter_by(sec_name=data).first_or_404()
    else:
        stock = stock_basics.query.filter_by(trade_code=data).first_or_404()
    return render_template("stock_solo/stock_solo_basic.html", current_user=current_user,stock=stock)

@stocksolo_blueprint.route('/finance_data',methods=('GET','POST'))
@stocksolo_blueprint.route('/finance_data/<string:data>',methods=('GET','POST'))
def finance_data(data='000895'):
    data=data
    form = CodeForm()
    if form.validate_on_submit():
        data = form.code.data
        return redirect(url_for('stock_solo.finance_data', current_user=current_user, data=data))
    match = zhPattern.search(data)
    if match:
        stock = stock_basics.query.filter_by(sec_name=data).first_or_404()
    else:
        stock = stock_basics.query.filter_by(trade_code=data).first_or_404()
    stock_list = []
    stock_source = stock_basics.query.all()
    for x in stock_source:
        stock_list.append(x.trade_code) # 这种写法没有括号

    year_list = []
    yearnow = time.strftime('%Y', time.localtime(time.time()))
    year_now = yearnow + '1231'
    year_now = int(year_now)-10000
    n = 26
    while n > 0:
        year_list.append(year_now)
        year_now = int(year_now) - 10000
        n = n - 1

    year_list_1 = year_list[:-1]

    results = []
    for t in year_list:
        result = finance_basics.query.filter_by(trade_code=data,the_year=(t)).first_or_404()
        results.append(result)

    ratio_RG = []
    for i in year_list_1:
        ratio_RG1 = finance_basics.query.filter_by(trade_code=data,the_year=(i)).first_or_404()
        ratio_RG2 = finance_basics.query.filter_by(trade_code=data,the_year=(i-10000)).first_or_404()
        if ratio_RG1.tot_oper_rev == None or ratio_RG2.tot_oper_rev == None or ratio_RG2.tot_oper_rev == 0 :
            ratio_RG.append(None) # 上边为什么有括号？？？
        else:
            ratio_test_RG = ratio_RG1.tot_oper_rev/ratio_RG2.tot_oper_rev
            ratio_RG.append(ratio_test_RG)

    ratio_CG = []
    for i in year_list_1:
        ratio_CG1 = finance_basics.query.filter_by(trade_code=data, the_year=(i)).first_or_404()
        ratio_CG2 = finance_basics.query.filter_by(trade_code=data, the_year=(i - 10000)).first_or_404()
        if ratio_CG1.wgsd_net_inc == None or ratio_CG2.wgsd_net_inc == None or ratio_CG2.wgsd_net_inc == 0:
            ratio_CG.append(None)
        else:
            ratio_test_CG = ratio_CG1.wgsd_net_inc / ratio_CG2.wgsd_net_inc
            ratio_CG.append(ratio_test_CG)

# 自动补全代码
    conn = MySQLdb.connect(user="root", passwd="0000", db="test", charset="utf8")
    cursor = conn.cursor()
    cursor.execute('select distinct trade_code,sec_name from finance_basics')
    value = cursor.fetchall()
    data_len = range(len(value))

    return render_template("stock_solo/stock_solo_finance_data.html",stock_list=stock_list, value=value, data_len=data_len, current_user=current_user,form=form, results=results, ratio_RG=ratio_RG, ratio_CG=ratio_CG)

@stocksolo_blueprint.route('/finance_data_yc', methods=('GET', 'POST'))
@stocksolo_blueprint.route('/finance_data_yc/<string:data>', methods=('GET', 'POST'))
@login_required
@permission_required(Permission.trader)
def finance_data_yc(data='000001'):
    if session.has_key('stockcode'):
        data = session['stockcode']
    else:
        data = '000001'
    if (request.method == 'POST'):
        stockcode = request.form.get("stockcode","000001")
        session['stockcode'] = stockcode
        return redirect(url_for('stock_solo.finance_data_yc', current_user=current_user, data=stockcode))
    return render_template("stock_solo/stock_solo_finance_data_yc.html",current_user=current_user,stockcode="\""+data+"\"")

@stocksolo_blueprint.route('/compare', methods=('GET', 'POST'))
@stocksolo_blueprint.route('/compare/<string:data>', methods=('GET', 'POST'))
@login_required
def compare():
    return render_template("stock_solo/stock_solo_compare.html",current_user=current_user)

@stocksolo_blueprint.route('/invest_value',methods=('GET','POST'))
@stocksolo_blueprint.route('/invest_value/<string:data>',methods=('GET','POST'))
# @login_required

def invest_value(data='000001'):
    if session.has_key('stockcode'):
        data = session['stockcode']
    else:
        data = '000001'
    if (request.method == 'POST'):
        stockcode=request.form.get("stockcode","000001")
        session['stockcode'] = stockcode
        return redirect(url_for('stock_solo.invest_value', current_user=current_user, data=stockcode))
    return render_template("stock_solo/finance_data.html",stockcode="\""+data+"\"")

# 正在维护的功能
@stocksolo_blueprint.route('/maintanance',methods=('GET','POST'))
def maintanance():
    return render_template("maintanance.html")

webapp/templates/stock_solo/first_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div id="container" style="margin:0 auto;width:70%;">
    <div id="first-line" style="width: 100%; height:130px;">
        <div style="border-left:2px solid #00008b; border-top: 2px solid #00008b; width:20%; height:100%; float:left;"><img src="{{ url_for('static',filename='resources/logo.png') }}" style="margin-top: 20px; margin-left: 20px;"></div>
        <div style="border-left:1px solid #00008b; border-top: 2px solid #00008b; border-right:2px solid #00008b; width:80%; height:100%; float:right;">
            <div style="border-top:1px;border-right: 1px;border-bottom: 2px ; background-color: orangered; width:100%; height:30%;margin-top: 90px;">
                <div class="panel-body" style="width: 14.28%; float: left;"><font style="color: white;">证券代码</font></div>
                <div class="panel-body" style="width: 14.28%; float: left;"><font style="color: white;">证券名称</font></div>
                <div class="panel-body" style="width: 14.28%; float: left;"><font style="color: white;">上市时间</font></div>
                <div class="panel-body" style="width: 14.28%; float: left;"><font style="color: white;">部门</font></div>
                <div class="panel-body" style="width: 14.28%; float: left;"> <font style="color: white;">行业组</font></div>
                <div class="panel-body" style="width: 14.28%; float: left;"><font style="color: white;">行业</font></div>
                <div class="panel-body" style="width: 14.28%; float: left;"><font style="color: white;">子行业</font></div>
            </div>
        </div>
    </div>

    <div id="second-line" style="width: 100%; height: 60%;">
    <div style="border-top:1px solid #00008b;border-left: 2px solid #00008b;border-bottom: 2px solid #00008b; width:20%; height:320px; float:left;"><font style="color: gray;">详细信息</font></div>
    <div style="border-left: 1px; width:80%; height:100%; float:right;">
        <div style="border-top:1px solid #00008b;border-left:1px solid #00008b; border-bottom:1px solid #00008b; border-right:2px solid #00008b;width:100%; height:60px;"></div>
        <div style="border-left:1px solid #00008b;border-right:2px solid #00008b;border-bottom:1px solid #00008b; width:100%; height:60px;">
            <div class="panel-body" style="width: 14.28%; float: left;">上市地点</div>
            <div class="panel-body" style="width: 14.28%; float: left;">所属版</div>
            <div class="panel-body" style="width: 14.28%; float: left;">交易币种</div>
            <div class="panel-body" style="width: 14.28%; float: left;">会计年结日</div>
            <div class="panel-body" style="width: 14.28%; float: left;">审计机构</div>
            <div class="panel-body" style="width: 14.28%; float: left;">省份</div>
            <div class="panel-body" style="width: 14.28%; float: left;">城市</div>
        </div>
        <div style="border-left:1px solid #00008b;border-right:2px solid #00008b;border-bottom:1px solid #00008b; width:100%; height:60px;">
            <div class="panel-body" style="width: 14.28%; float: left;">成立时间</div>
            <div class="panel-body" style="width: 14.28%; float: left;">公司属性</div>
            <div class="panel-body" style="width: 14.28%; float: left;">董事长</div>
            <div class="panel-body" style="width: 28.56%; float: left;">实际控制人</div>
            <div class="panel-body" style="width: 14.28%; float: left;">公司网站</div>
            <div class="panel-body" style="width: 14.28%; float: left;">联系电话</div>
        </div>
        <div style="border-left:1px solid #00008b;border-right:2px solid #00008b;border-bottom:2px solid #00008b; width:100%; height:140px;">
            <div class="panel-body" style="width: 20%; float: left;">主营产品类型</div><br><br><br><br>
            <div class="panel-body" style="width: 20%; float: left;">主营产品名称</div>
        </div>
        </div>
    </div>
<!--写入..就能正常显示图片了-->
</div>
</body>
</html>
<SCRIPT Language=VBScript><!--

//--></SCRIPT>

webapp/templates/stock_solo/stock_solo_base.html
{% if current_user.is_authenticated %}
    {% extends "stock_base.html" %}
{% else %}
    {% extends "stock_base_visitor.html" %}
{% endif %}
{% block searchForm %}
    <form id="searchform" class="navbar-search pull-left input-append" role="search" method="post"
          action="{{ url_for('stock_solo.basic') }}">
        <div class="input-group">
            <input type="text" class="span3 form-control" id="stockcode" style="height: 30px"
                   placeholder="Search" name="stockcode">
            <button id="submitbtn" class="btn dropdown-toggle" style="height: 30px" data-toggle="dropdown"
                    type="submit"><i class="icon-search"></i></button>
            <ul class="dropdown-menu" role="menu" style="left: 0!important;"></ul>
        </div>
    </form>
{% endblock %}
{% block JavaScripts %}
    <script>
        var stocksuggest = $("input[name='stockcode']").bsSuggest({
            indexKey: 1,
            allowNoKeyword: false,
            getDataMethod: "url",
            url: '{{url_for("restfulapi.stock_code",q="")}}',
            processData: function (json) {     // url 获取数据时，对数据的处理，作为 getData 的回调函数
                var i, len, data = {value: []};
                if (!json || !json.stockcode || json.stockcode.length == 0) {
                    return false;
                }
                len = json.stockcode.length;
                for (i = 0; i < len; i++) {
                    data.value.push({
                        "Id": (i + 1),
                        "stockcode": json.stockcode[i],
                        "stockname": json.stockname[i],
                        "jianpin":json.jianpin[i]
                    });
                }
                return data;
            }
        });
        $("#submitbtn").click(function () {
            $.ajax({
                type: 'POST',
                url: '{{url_for("restfulapi.iscode")}}',
                data: {
                    'code': $("#stockcode").val(),
                },
                dataType: 'json',
                success: function (data) {
                    if (data.the_name != 'false') {
                        $("#searchform").submit();
                    }
                    else {
                        alert($("#stockcode").val() + "号股票不存在！")
                    }
                }
            })
        })
        $(function () {
            $("[data-toggle='tooltip']").tooltip();
        });
    </script>
    {% block scripts %}{% endblock %}
{% endblock %}

webapp/templates/stock_solo/stock_solo_basic_old.html
{% extends "stock_solo/stock_solo_base.html" %}
{% block form %}
    <form class="form-search" method="POST" action="{{ url_for('stock_solo.basic') }}">
        {{ form.hidden_tag() }}
        {{ form.code(id='tags',class_='input-sm',placeholder='输入股票代号或名称',title="内含自动补全功能，输入关键字即可补全股票代码或名称") }}
        <input class="btn btn-success btn-xs" type="submit" value="搜索" contenteditable="true" data-toggle="tooltip"
               title="内含自动补全功能，输入关键字即可补全股票代码或名称" data-placement="right">
    </form>
    <script>
        $(function () {
            $("[data-toggle='tooltip']").tooltip();
        });
    </script> <!--用于实现“右侧提示框”-->
{% endblock %}

{% block tab %}
    <ul class="nav nav-pills">
        <li class="active"><a href="{{ url_for('stock_solo.basic') }}">基本情况</a></li>
        <li><a href="{{ url_for('stock_solo.finance_data_yc') }}">财务数据及分析</a></li>
        <li><a href="{{ url_for('stock_solo.invest_value') }}">投资价值分析</a></li>
        <li><a href="{{ url_for('stock_solo.compare') }}">股票对比分析</a></li>
    </ul>
{% endblock %}

{% block chart %}
    <div id="map">

    </div>

{% endblock %}

{% block table %}
    <table class="auto-style1" align="center"
           style="width:100%;height: 100%; border-width: 2px; border-style: solid; border-color: #000000; background-color: #FFFFFF; font-family: 宋体, Arial, Helvetica, sans-serif; font-size: 10px;">
        <tr style="height: 15%">
            <td rowspan="2"
                style="text-align:center; width:15%; border-style: solid; border-width: thin; border-color: #000000;">
                <img src="../static/logo.png"></td>
            <td colspan="7">&nbsp;</td>
        </tr>
        <tr style="height: 10%">
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">证券代码</td>
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">证券名称</td>
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">上市时间</td>
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">部门</td>
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">行业组</td>
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">行业</td>
            <td class="auto-style3" style="width: 12%;background-color: #FF3300; color: #FFFFFF;">子行业</td>
        </tr>
        <tr>
            <td rowspan="7" style="border:1px solid;">&nbsp;</td>
            <td>{{ stock.trade_code }}</td>
            <td>{{ stock.sec_name }}</td>
            <td>{{ stock.ipo_date }}</td>
            <td></td>
            <td></td>
            <td>{{ stock.industry_gics }}</td>
            <td></td>
        </tr>
        <tr>
            <td>上市地点</td>
            <td>所属板块</td>
            <td>交易币种</td>
            <td>会计年结日</td>
            <td>审计机构</td>
            <td>省份</td>
            <td>城市</td>
        </tr>
        <tr>
            <td>{{ stock.exch_city }}</td>
            <td>&nbsp;</td>
            <td>{{ stock.curr }}</td>
            <td>{{ stock.fiscaldate }}</td>
            <td>{{ stock.auditor }}</td>
            <td>{{ stock.province }}</td>
            <td>{{ stock.city }}</td>
        </tr>
        <tr>
            <td class="auto-style2">成立时间</td>
            <td class="auto-style2">公司属性</td>
            <td class="auto-style2">董事长</td>
            <td class="auto-style2" colspan="2">实际控制人</td>
            <td class="auto-style2">公司网站</td>
            <td class="auto-style2">联系电话</td>
        </tr>
        <tr>
            <td>{{ stock.founddate }}</td>
            <td>{{ stock.concept }}</td>
            <td>{{ stock.boardchairmen }}</td>
            <td>{{ stock.holder_controller }}</td>
            <td></td><!--需要合并单元格-->
            <td>{{ stock.website }}</td>
            <td>{{ stock.phone }}</td>
        </tr>
        <tr>
            <td>主营产品类型</td>
            <td colspan="6">{{ stock.majorproducttype }}</td>
        </tr>
        <tr>
            <td class="auto-style2">主营产品名称</td>
            <td class="auto-style2" colspan="6">{{ stock.majorproductname }}</td>
        </tr>
    </table>
{% endblock %}

<SCRIPT Language=VBScript><!--

//-->


</SCRIPT>

webapp/templates/stock_solo/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ search_year }}
<form class="form-search" method="POST" action="{{ url_for('stock_solo.graph') }}">
        {{ graph_form.hidden_tag() }}
        {{ graph_form.graph_id(class_='input-sm') }}
        {{ graph_form.year_id(class_='input-sm') }}
        <input class="btn btn-success btn-sm" type="submit" value="画图" contenteditable="true">
    </form>
</body>
</html><SCRIPT Language=VBScript><!--

//--></SCRIPT>