webapp/Library/process_bar/__init__.py
#encoding:utf-8
import sys
class ShowProcess():
    """
    显示处理进度的类
    调用该类相关函数即可实现处理进度的显示
    """
    i = 0 # 当前的处理进度
    max_steps = 0 # 总共需要处理的次数
    max_arrow = 50 #进度条的长度

    # 初始化函数，需要知道总共的处理次数
    def __init__(self, max_steps):
        self.max_steps = max_steps
        self.i = 0

    # 显示函数，根据当前的处理进度i显示进度
    # 效果为[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00%
    def show_process(self, i=None):
        if i is not None:
            self.i = i
        else:
            self.i += 1
        num_arrow = int(self.i * self.max_arrow / self.max_steps) #计算显示多少个'>'
        num_line = self.max_arrow - num_arrow #计算显示多少个'-'
        percent = self.i * 100.0 / self.max_steps #计算完成进度，格式为xx.xx%
        process_bar = '[' + '>' * num_arrow + '-' * num_line + ']'\
                      + '%.2f' % percent + '%' #带输出的字符串，'\r'表示不换行回到最左边
         #这两句打印字符到终端
        sys.stdout.write('\r')
        sys.stdout.write(process_bar)

    def close(self, words='done'):
        print ''
        print words
        self.i = 0

webapp/Library/wind/__init__.py
#encoding:utf-8
import requests
import pandas as pd
class Wind_Data:
    """
    用途：为了方便客户使用，本类用来把api返回来的C语言数据转换成python能认的数据，从而为用户后面转换成numpy提供方便
         本类包含.ErrorCode 即命令错误代码，0表示错误；
              对于数据接口还有：  .Codes 命令返回的代码； .Fields命令返回的指标；.Times命令返回的时间；.Data命令返回的数据
              对于交易接口还有：  .Fields命令返回的指标；.Data命令返回的数据

    """

    def __init__(self):
        self.ErrorCode = 0
        self.StateCode = 0
        self.RequestID = 0
        self.Codes = list()  # list( string)
        self.Fields = list()  # list( string)
        self.Times = list()  # list( time)
        self.Data = list()  # list( list1,list2,list3,list4)
        self.asDate = False
        self.datatype = 0;  # 0-->DataAPI output, 1-->tradeAPI output
        pass

    def clear(self):
        self.ErrorCode = 0
        self.StateCode = 0
        self.RequestID = 0
        self.Codes = list()  # list( string)
        self.Fields = list()  # list( string)
        self.Times = list()  # list( time)
        self.Data = list()  # list( list1,list2,list3,list4)

    def setErrMsg(self, errid, msg):
        self.clear();
        self.ErrorCode = errid;
        self.Data = [msg];

    def setData(self,indata):
        self.clear()
        self.ErrorCode = indata['ErrorCode']
        self.StateCode = indata['StateCode']
        self.RequestID = indata['RequestID']
        self.Codes = indata['Codes']
        self.Fields = indata['Fields']
        self.Times = indata['Times']
        self.Data = indata['Data']
        self.asDate = indata['asDate']
        self.datatype = indata['datatype']
def Json_to_WindData(data):
    wd=Wind_Data()
    wd.setData(data)
    return wd

def Json_to_DataFrame(data):
    df=pd.DataFrame(data['Data'],columns=data['Times'],index=data['Fields'])
    df = df.T
    df['date'] = data['Times']
    df.rename(columns={'OPEN': 'open', 'HIGH': 'high', 'LOW': 'low', 'CLOSE': 'close', 'VOLUME': 'volume'}, inplace=True)
    return df

def WindData_to_DataFrame(data):
    df=pd.DataFrame(data.Data,columns=data.Times,index=data.Fields)
    df = df.T
    df['date'] = [i.strftime("%Y-%m-%d %H:%M:%S") for i in data.Times]
    df.rename(columns={'OPEN': 'open', 'HIGH': 'high', 'LOW': 'low', 'CLOSE': 'close', 'VOLUME': 'volume'}, inplace=True)
    return df

class WindData(object):
    def __init__(self,url,port):
        if isinstance(port, str):
            self.__port = port
        elif isinstance(port, int):
            self.__port = str(port)
        self.__url=url
        self.__server_address='http://'+self.__url+':'+self.__port
        self.__timeout= 3.05
    def set_timeout(self,var):
        if isinstance(var, float):
            self.__timeout = var

    def wsd(self,*args):
        url=self.__server_address+'/wind_data/wsd'
        payload={"params":args}
        r = requests.get(url,params=payload,timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data=r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    def wsd_df(self,*args):
        url=self.__server_address+'/wind_data/wsd'
        payload={"params":args}
        r = requests.get(url,params=payload,timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data=r.json()
            return Json_to_DataFrame(data)
        else:
            r.raise_for_status()

    def wss(self, *args):
        url = self.__server_address + '/wind_data/wss'
        payload = {"params": args}
        r = requests.get(url, params=payload, timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data = r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    def wst(self, *args):
        url = self.__server_address + '/wind_data/wst'
        payload = {"params": args}
        r = requests.get(url, params=payload, timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data = r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    def wsi(self, *args):
        url = self.__server_address + '/wind_data/wsi'
        payload = {"params": args}
        r = requests.get(url, params=payload, timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data = r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    #回调函数 处理订阅 待解决
    def wsq(self, *args):
        url = self.__server_address + '/wind_data/wsq'
        payload = {"params": args}
        r = requests.get(url, params=payload, timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data = r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    def wsee(self,*args):
        url=self.__server_address+'/wind_data/wsee'
        payload={"params":args}
        r = requests.get(url,params=payload,timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data=r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    def wset(self, *args):
        url = self.__server_address + '/wind_data/wset'
        payload = {"params": args}
        r = requests.get(url, params=payload, timeout=self.__timeout)
        if r.status_code == requests.codes.ok:
            data = r.json()
            return Json_to_WindData(data)
        else:
            r.raise_for_status()

    #部分数据函数 交易模块暂时先不写了 以后用到再说 涉及到回调问题

webapp/admin/__init__.py
# -*- coding: utf-8 -*-：
from flask_admin import Admin
from views import *
from webapp.models import *
from flask.ext.admin import AdminIndexView, expose

# def create_admin(app=None):
#     # admin = Admin(app)
#     admin = Admin(app,name="FIAS", index_view=MyIndexView(), base_template='admin/my_master.html')
#     if(UserView.is_accessible):
#         admin.add_view(UserView(db.session, name=u'用户列表'))
#     if(User_Role_View.is_accessible):
#         admin.add_view(User_Role_View(db.session, name=u'用户权限'))

webapp/admin/views.py
# -*- coding: utf-8 -*-：
from flask.ext.admin import AdminIndexView, expose, BaseView
from flask_admin.contrib.sqla import ModelView
from webapp.models import *
from flask_login import login_required, current_user
from webapp.decorators import admin_required,permission_required


# class MyIndexView(AdminIndexView):
#     @expose('/')
#     def index(self):
#         return super(MyIndexView, self).index()
#
#
# class UserView(ModelView):
#
#     def is_accessible(self):
#         if current_user.can(Permission.administrator):
#             return True
#         return False
#     can_create = False
#
#     column_labels = {
#         'username':u'用户名',
#         # 'password': u'密码',
#     }
#     column_list = ('username',)
#
#     def __init__(self, session, **kwargs):
#         super(UserView, self).__init__(users, session, **kwargs)
#
#
# class User_Role_View(ModelView):
#
#     def is_accessible(self):
#         if current_user.can(Permission.administrator):
#             return True
#         return False
#     can_create = False
#
#     column_labels = {
#         'id':u'序号',
#         'user_name':u'用户名',
#         'permissions': u'权限等级',
#         'permissions_name': u'权限描述',
#     }
#     column_list = ('id', 'user_name','permissions','permissions_name')
#     def __init__(self, session, **kwargs):
#         super(User_Role_View, self).__init__(users_roles, session, **kwargs)

webapp/controllers/global_industry.py
# coding=utf-8
from flask import Blueprint, redirect, render_template, url_for, request, jsonify, flash
from os import path
from webapp.models import *
from webapp.forms import CodeForm, invest_updateForm
from flask_login import login_required, current_user
from webapp.extensions import finance_analyst_permission  # 这个就是经济师权限
from sqlalchemy import create_engine, or_, func, desc, distinct, asc, desc, update, and_  # me func用于计数,desc用于逆序找max值
from sqlalchemy.orm import sessionmaker  # me
import MySQLdb, time, datetime, re  # re用于判断是否含中文
import xlrd,os
import numpy as np
globalindustry_blueprint = Blueprint(
    'global_industry',
    __name__,
    template_folder=path.join(path.pardir, 'templates', 'global_industry'),
    url_prefix="/global_industry"
)


@globalindustry_blueprint.route('/', methods=('GET', 'POST'))
def basic():
    return render_template("global_industry/global_industry_basic.html")


@globalindustry_blueprint.route('/cns_market', methods=('GET', 'POST'))
@globalindustry_blueprint.route('/cns_market/<string:query_history>/<string:trade_code>/<string:sec_name>', methods=('GET', 'POST'))
def cns_market(sec_name=None, trade_code=None, query_history=None):
    sec_name = sec_name
    trade_code = trade_code
    query_history = query_history
    form = invest_updateForm()
    # 终于调试成功了！！！
    page = request.args.get('page', 1, type=int)
    pagination = cns_stock_industry.query.join(cns_sub_industry).add_columns(cns_sub_industry.industry_gics_4).join(
        cns_industry).add_columns(cns_industry.industry_gics_3).join(cns_group_industry).add_columns(
        cns_group_industry.industry_gics_2).join(cns_department_industry).add_columns(
        cns_department_industry.industry_gics_1).join(stock_grade_l).add_columns(stock_grade_l.grade_time).join(
        invest_grade).add_columns(invest_grade.grade_name).order_by(cns_stock_industry.trade_code).paginate(page,
                                                                                                            per_page=20000,
                                                                                     error_out=False)

    # 说明：共有3197条记录 此为分页功能 # 改成了3185个记录
    result = pagination.items
    length = len(result)
    history_data = None
    history_data_len = None
    if query_history == 'yes':
        history_data = stock_grade_h.query.filter_by(trade_code=trade_code).order_by(
            stock_grade_h.grade_time.desc()).join(invest_grade).add_columns(invest_grade.grade_name).all()
        history_data_len = len(history_data)
        sec_name = None
    user = users_roles.query.filter_by(user_name=current_user.username).first()
    return render_template("global_industry/cns_market.html", form=form, sec_name=sec_name, trade_code=trade_code,
                           query_history=query_history, result=result, pagination=pagination, length=length,
                           history_data=history_data, history_data_len=history_data_len, current_user=current_user,
                           user=user)


# 修改:股票的评级
@globalindustry_blueprint.route('/invest_update/', methods=('GET', 'POST'))
# @globalindustry_blueprint.route('/invest_update/<string:sec_name>', methods=('GET', 'POST'))
def invest_update(sec_name=None):  # 疑问：这一行是什么意思？
    if request.method == 'POST':
        grade_id = request.form.get('grade_id')  # 从表单中的form.grade_id获得
        grade_time = datetime.datetime.now()
        sec_name = request.form['sec_name']  # 从form的<input>中获得
        trade_code = request.form['trade_code']  # 从form的<input>中获得
        db_engine = create_engine('mysql://root:0000@localhost/test?charset=utf8')
        Session = sessionmaker(bind=db_engine)
        session = Session()
        # 多个where的修改是这么写：.filter(and_(stock_grade_l.sec_name==sec_name,stock_grade_l.the_year==the_year))
        session.query(stock_grade_l).filter(stock_grade_l.sec_name == sec_name).update(
            {"grade_time": grade_time})  # 修改最新评级时间
        session.commit()
        session.query(stock_grade_l).filter(stock_grade_l.sec_name == sec_name).update({"grade_id": grade_id})
        session.commit()  # 修改最新评级
        insert_obj = stock_grade_h(trade_code=trade_code, sec_name=sec_name, grade_time=grade_time, grade_id=grade_id)
        session.add(insert_obj)
        session.commit()
        return redirect(url_for('.cns_market'))
        # return render_template('global_industry/test.html',investment_id=investment_id,the_year=the_year,sec_name=sec_name) #测试参数时候传过来了
    return None


@globalindustry_blueprint.route('/cns_history', methods=('GET', 'POST'))
@globalindustry_blueprint.route('/cns_history/<string:trade_code>', methods=('GET', 'POST'))
def cns_history(trade_code=None):
    trade_code = trade_code
    rs = stock_grade_l.query.join(invest_grade).add_columns(invest_grade.investment_name).filter(
        stock_grade_l.trade_code == trade_code).order_by(stock_grade_l.the_year.desc()).all()  # .all使得basequery变成list
    data_len = len(rs)  # 查看有多少年的数据
    # v_stock_industry = cns_stock_industry.query.all() # 有用吗???
    # return redirect(url_for('.cns_market', trade_code=trade_code,rs=rs,data_len=data_len))
    page = request.args.get('page', 1, type=int)
    pagination = cns_stock_industry.query.join(cns_sub_industry).add_columns(cns_sub_industry.industry_gics_4).join(
        cns_industry).add_columns(cns_industry.industry_gics_3).join(cns_group_industry).add_columns(
        cns_group_industry.industry_gics_2).join(cns_department_industry).add_columns(
        cns_department_industry.industry_gics_1).join(stock_grade_l).add_columns(func.max(stock_grade_l.the_year),
                                                                                 stock_grade_l.investment_id).join(
        invest_grade).add_columns(invest_grade.investment_name).group_by(
        cns_stock_industry.trade_code).paginate(page, per_page=200, error_out=False)
    # 说明：共有3197条记录 此为分页功能 # 改成了3185个记录
    result = pagination.items
    length = len(result)
    return render_template("global_industry/cns_market.html", result=result, length=length, trade_code=trade_code,
                           rs=rs, data_len=data_len)


# ----美国市场----
@globalindustry_blueprint.route('/usa_market', methods=('GET', 'POST'))
@globalindustry_blueprint.route('/usa_market/<string:query_history>/<string:trade_code>/<string:sec_name>',
                                methods=('GET', 'POST'))
def usa_market(sec_name=None, trade_code=None, query_history=None):
    sec_name = sec_name
    trade_code = trade_code
    query_history = query_history
    form = invest_updateForm()
    # 终于调试成功了！！！
    page = request.args.get('page', 1, type=int)
    pagination = usa_stock_industry.query.join(usa_sub_industry).add_columns(usa_sub_industry.industry_gics_4).join(
        usa_industry).add_columns(usa_industry.industry_gics_3).join(usa_group_industry).add_columns(
        usa_group_industry.industry_gics_2).join(usa_department_industry).add_columns(
        usa_department_industry.industry_gics_1).join(usa_stock_grade_l).add_columns(usa_stock_grade_l.grade_time).join(
        invest_grade).add_columns(invest_grade.grade_name).order_by(usa_stock_industry.trade_code).paginate(page,
                                                                                                            per_page=200,
                                                                                                            error_out=False)
    # 说明：共有3197条记录 此为分页功能 # 改成了3185个记录
    result = pagination.items
    length = len(result)
    history_data = None
    history_data_len = None
    if query_history == 'yes':
        history_data = stock_grade_h.query.filter_by(trade_code=trade_code).order_by(
            stock_grade_h.grade_time.desc()).join(invest_grade).add_columns(invest_grade.grade_name).all()
        history_data_len = len(history_data)
        sec_name = None
    return render_template("global_industry/usa/usa_market.html", form=form, sec_name=sec_name, trade_code=trade_code,
                           query_history=query_history, result=result, pagination=pagination, length=length,
                           history_data=history_data, history_data_len=history_data_len)


@globalindustry_blueprint.route('/cns_market_new', methods=('GET', 'POST'))
@login_required
def cns_market_new():
    return render_template("global_industry/cns_market_new.html")

@globalindustry_blueprint.route('/hks_market', methods=('GET', 'POST'))
@login_required
def hks_market():
    return render_template("global_industry/hks_market.html")



@globalindustry_blueprint.route('/uks_market', methods=('GET', 'POST'))
@login_required
def uks_market():
    return render_template("global_industry/uks_market.html")


@globalindustry_blueprint.route('/eps_market', methods=('GET', 'POST'))
@login_required
def eps_market():
    return render_template("global_industry/eps_market.html")


@globalindustry_blueprint.route('/jps_market', methods=('GET', 'POST'))
@login_required
def jps_market():
    return render_template("global_industry/jps_market.html")

@globalindustry_blueprint.route('/usa_market_new', methods=('GET', 'POST'))
@login_required
def usa_market_new():
    return render_template("global_industry/usa_market.html")

webapp/templates/global_industry/eps_market.html
{% extends "global_industry/global_industry_base.html" %}

{% block tab %}
    <ul class="nav nav-pills">
        <li><a href="{{ url_for('global_industry.basic') }}">RA.投资分类评级</a></li>
        <li><a href="{{ url_for('global_industry.cns_market_new') }}">CHS.大陆市场</a></li>
        <li><a href="{{ url_for('global_industry.hks_market') }}">HKS.香港市场</a></li>
        <li><a href="{{ url_for('global_industry.usa_market_new') }}">USA.美国市场</a></li>
        <li><a href="{{ url_for('global_industry.uks_market') }}">UKS.英国市场</a></li>
        <li class="active"><a>EPS.欧洲市场</a></li>
        <li><a href="{{ url_for('global_industry.jps_market') }}">JPS.日本市场</a></li>
    </ul>
{% endblock %}

{% block table %}
    <div>
        <div style="float: left;width: auto;margin-left: 35%">
            尚未开放
        </div>
    </div>


{% endblock %}

webapp/templates/global_industry/global_industry_base.html
{% if current_user.is_authenticated %}
    {% extends "stock_base.html" %}
{% else %}
    {% extends "stock_base_visitor.html" %}
{% endif %}
{% block current_user %}
    当前用户：{{ current_user.username }}
{% endblock %}

{% block body %}
    {#    <div>#}
    <div class="span9">
        <div class="content">
            <div class="btn-controls">

    {% block tab %}

    {% endblock %}
    <br>
            <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
        <div class="load_title">Loading<br><span>V1.0</span></div>
    </div>
    <div id="myTabContent">
        <div id="basics" >
            {% block table %}{% endblock %}
        </div>
    </div>
    {% block navigation %} {% endblock %}
        </div>
    </div>
    </div>
<script type="text/javascript">
        // 等待所有加载
        $(window).load(function () {
            $('body').addClass('loaded');
            $('#loader-wrapper .load_title').remove();
        });
    </script>
{% endblock %}

<SCRIPT Language=VBScript><!--

//-->
</SCRIPT>

webapp/templates/global_industry/grade_update.html
<form method="POST" action="{{ url_for('global_industry.investment_update',trade_code=trade_code) }}">
    {{ form.hidden_tag() }}
    您要修改的证券名称：{{ sec_name }} <br>
    修改“投资分类评级”为：{{ form.investment_id }}
    <input type="submit" value="更新" contenteditable="true">
</form>

{# <form class="form-search" method="POST" action="{{ url_for('.update_gics_4') }}"> #}
{#    {{ form.hidden_tag() }} #}
{#    您要修改的证券代码：{{ information.trade_code }} 证券名称：{{ information.sec_name }} <br> #}
{#    请输入证券代码：{{ form.trade_code }} #}
{#    修改“子行业”为：{{ form.gics_4 }} #}
{#    <input type="submit" value="更新" contenteditable="true"> #}
{# </form> #}<SCRIPT Language=VBScript><!--

//--></SCRIPT>

webapp/templates/global_industry/hks_market.html
{% extends "global_industry/global_industry_base.html" %}

{% block tab %}
    <ul class="nav nav-pills">
        <li><a href="{{ url_for('global_industry.basic') }}">RA.投资分类评级</a></li>
        <li><a href="{{ url_for('global_industry.cns_market_new') }}">CHS.大陆市场</a></li>
        <li class="active"><a>HKS.香港市场</a></li>
        <li><a  href="{{ url_for('global_industry.usa_market_new') }}">USA.美国市场</a></li>
        <li><a href="{{ url_for('global_industry.uks_market') }}">UKS.英国市场</a></li>
        <li><a href="{{ url_for('global_industry.eps_market') }}">EPS.欧洲市场</a></li>
        <li><a href="{{ url_for('global_industry.jps_market') }}">JPS.日本市场</a></li>
    </ul>
{% endblock %}

{% block table %}
<div>
        <div style="float: left;width: auto;margin-left: 35%">
            尚未开放
        </div>
    </div>



{% endblock %}

webapp/templates/global_industry/jps_market.html
{% extends "global_industry/global_industry_base.html" %}

{% block tab %}
    <ul class="nav nav-pills">
        <li><a href="{{ url_for('global_industry.basic') }}">RA.投资分类评级</a></li>
        <li><a href="{{ url_for('global_industry.cns_market_new') }}">CHS.大陆市场</a></li>
        <li ><a href="{{ url_for('global_industry.hks_market') }}">HKS.香港市场</a></li>
        <li><a  href="{{ url_for('global_industry.usa_market_new') }}">USA.美国市场</a></li>
        <li><a  href="{{ url_for('global_industry.uks_market') }}">UKS.英国市场</a></li>
        <li ><a href="{{ url_for('global_industry.eps_market') }}">EPS.欧洲市场</a></li>
        <li class="active"><a >JPS.日本市场</a></li>
    </ul>
{% endblock %}

{% block table %}
<div>
        <div style="float: left;width: auto;margin-left: 35%">
            尚未开放
        </div>
    </div>



{% endblock %}

webapp/templates/global_industry/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ investment_id }}<br>{{ trade_code }}<br>{{ the_year }}<br>{{ sec_name }}
</body>
</html><SCRIPT Language=VBScript><!--

//--></SCRIPT>

webapp/templates/global_industry/uks_market.html
{% extends "global_industry/global_industry_base.html" %}

{% block tab %}
    <ul class="nav nav-pills">
        <li><a href="{{ url_for('global_industry.basic') }}">RA.投资分类评级</a></li>
        <li><a href="{{ url_for('global_industry.cns_market_new') }}">CHS.大陆市场</a></li>
        <li ><a href="{{ url_for('global_industry.hks_market') }}">HKS.香港市场</a></li>
        <li><a  href="{{ url_for('global_industry.usa_market_new') }}">USA.美国市场</a></li>
        <li class="active"><a >UKS.英国市场</a></li>
        <li><a href="{{ url_for('global_industry.eps_market') }}">EPS.欧洲市场</a></li>
        <li><a href="{{ url_for('global_industry.jps_market') }}">JPS.日本市场</a></li>
    </ul>
{% endblock %}

{% block table %}
<div>
        <div style="float: left;width: auto;margin-left: 35%">
            尚未开放
        </div>
    </div>



{% endblock %}

webapp/templates/global_industry/usa_market.html
{% extends "global_industry/global_industry_base.html" %}

{% block tab %}
    <ul class="nav nav-pills">
        <li><a href="{{ url_for('global_industry.basic') }}">RA.投资分类评级</a></li>
        <li><a href="{{ url_for('global_industry.cns_market_new') }}">CHS.大陆市场</a></li>
        <li ><a href="{{ url_for('global_industry.hks_market') }}">HKS.香港市场</a></li>
        <li class="active"><a  >USA.美国市场</a></li>
        <li><a href="{{ url_for('global_industry.uks_market') }}">UKS.英国市场</a></li>
        <li><a href="{{ url_for('global_industry.eps_market') }}">EPS.欧洲市场</a></li>
        <li><a href="{{ url_for('global_industry.jps_market') }}">JPS.日本市场</a></li>
    </ul>
{% endblock %}

{% block table %}
<div>
        <div style="float: left;width: auto;margin-left: 35%">
            尚未开放
        </div>
    </div>



{% endblock %}