webapp/Library/process_bar/__init__.py
#encoding:utf-8
import sys
class ShowProcess():
    """
    显示处理进度的类
    调用该类相关函数即可实现处理进度的显示
    """
    i = 0 # 当前的处理进度
    max_steps = 0 # 总共需要处理的次数
    max_arrow = 50 #进度条的长度

    # 初始化函数，需要知道总共的处理次数
    def __init__(self, max_steps):
        self.max_steps = max_steps
        self.i = 0

    # 显示函数，根据当前的处理进度i显示进度
    # 效果为[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00%
    def show_process(self, i=None):
        if i is not None:
            self.i = i
        else:
            self.i += 1
        num_arrow = int(self.i * self.max_arrow / self.max_steps) #计算显示多少个'>'
        num_line = self.max_arrow - num_arrow #计算显示多少个'-'
        percent = self.i * 100.0 / self.max_steps #计算完成进度，格式为xx.xx%
        process_bar = '[' + '>' * num_arrow + '-' * num_line + ']'\
                      + '%.2f' % percent + '%' #带输出的字符串，'\r'表示不换行回到最左边
         #这两句打印字符到终端
        sys.stdout.write('\r')
        sys.stdout.write(process_bar)

    def close(self, words='done'):
        print ''
        print words
        self.i = 0

webapp/controllers/global_industry.py
# coding=utf-8
from flask import Blueprint, redirect, render_template, url_for, request, jsonify, flash
from os import path
from webapp.models import *
from webapp.forms import CodeForm, invest_updateForm
from flask_login import login_required, current_user
from webapp.extensions import finance_analyst_permission  # 这个就是经济师权限
from sqlalchemy import create_engine, or_, func, desc, distinct, asc, desc, update, and_  # me func用于计数,desc用于逆序找max值
from sqlalchemy.orm import sessionmaker  # me
import MySQLdb, time, datetime, re  # re用于判断是否含中文
import xlrd,os
import numpy as np
globalindustry_blueprint = Blueprint(
    'global_industry',
    __name__,
    template_folder=path.join(path.pardir, 'templates', 'global_industry'),
    url_prefix="/global_industry"
)


@globalindustry_blueprint.route('/', methods=('GET', 'POST'))
def basic():
    return render_template("global_industry/global_industry_basic.html")


@globalindustry_blueprint.route('/cns_market', methods=('GET', 'POST'))
@globalindustry_blueprint.route('/cns_market/<string:query_history>/<string:trade_code>/<string:sec_name>', methods=('GET', 'POST'))
def cns_market(sec_name=None, trade_code=None, query_history=None):
    sec_name = sec_name
    trade_code = trade_code
    query_history = query_history
    form = invest_updateForm()
    # 终于调试成功了！！！
    page = request.args.get('page', 1, type=int)
    pagination = cns_stock_industry.query.join(cns_sub_industry).add_columns(cns_sub_industry.industry_gics_4).join(
        cns_industry).add_columns(cns_industry.industry_gics_3).join(cns_group_industry).add_columns(
        cns_group_industry.industry_gics_2).join(cns_department_industry).add_columns(
        cns_department_industry.industry_gics_1).join(stock_grade_l).add_columns(stock_grade_l.grade_time).join(
        invest_grade).add_columns(invest_grade.grade_name).order_by(cns_stock_industry.trade_code).paginate(page,
                                                                                                            per_page=20000,
                                                                                     error_out=False)

    # 说明：共有3197条记录 此为分页功能 # 改成了3185个记录
    result = pagination.items
    length = len(result)
    history_data = None
    history_data_len = None
    if query_history == 'yes':
        history_data = stock_grade_h.query.filter_by(trade_code=trade_code).order_by(
            stock_grade_h.grade_time.desc()).join(invest_grade).add_columns(invest_grade.grade_name).all()
        history_data_len = len(history_data)
        sec_name = None
    user = users_roles.query.filter_by(user_name=current_user.username).first()
    return render_template("global_industry/cns_market.html", form=form, sec_name=sec_name, trade_code=trade_code,
                           query_history=query_history, result=result, pagination=pagination, length=length,
                           history_data=history_data, history_data_len=history_data_len, current_user=current_user,
                           user=user)


# 修改:股票的评级
@globalindustry_blueprint.route('/invest_update/', methods=('GET', 'POST'))
# @globalindustry_blueprint.route('/invest_update/<string:sec_name>', methods=('GET', 'POST'))
def invest_update(sec_name=None):  # 疑问：这一行是什么意思？
    if request.method == 'POST':
        grade_id = request.form.get('grade_id')  # 从表单中的form.grade_id获得
        grade_time = datetime.datetime.now()
        sec_name = request.form['sec_name']  # 从form的<input>中获得
        trade_code = request.form['trade_code']  # 从form的<input>中获得
        db_engine = create_engine('mysql://root:0000@localhost/test?charset=utf8')
        Session = sessionmaker(bind=db_engine)
        session = Session()
        # 多个where的修改是这么写：.filter(and_(stock_grade_l.sec_name==sec_name,stock_grade_l.the_year==the_year))
        session.query(stock_grade_l).filter(stock_grade_l.sec_name == sec_name).update(
            {"grade_time": grade_time})  # 修改最新评级时间
        session.commit()
        session.query(stock_grade_l).filter(stock_grade_l.sec_name == sec_name).update({"grade_id": grade_id})
        session.commit()  # 修改最新评级
        insert_obj = stock_grade_h(trade_code=trade_code, sec_name=sec_name, grade_time=grade_time, grade_id=grade_id)
        session.add(insert_obj)
        session.commit()
        return redirect(url_for('.cns_market'))
        # return render_template('global_industry/test.html',investment_id=investment_id,the_year=the_year,sec_name=sec_name) #测试参数时候传过来了
    return None


@globalindustry_blueprint.route('/cns_history', methods=('GET', 'POST'))
@globalindustry_blueprint.route('/cns_history/<string:trade_code>', methods=('GET', 'POST'))
def cns_history(trade_code=None):
    trade_code = trade_code
    rs = stock_grade_l.query.join(invest_grade).add_columns(invest_grade.investment_name).filter(
        stock_grade_l.trade_code == trade_code).order_by(stock_grade_l.the_year.desc()).all()  # .all使得basequery变成list
    data_len = len(rs)  # 查看有多少年的数据
    # v_stock_industry = cns_stock_industry.query.all() # 有用吗???
    # return redirect(url_for('.cns_market', trade_code=trade_code,rs=rs,data_len=data_len))
    page = request.args.get('page', 1, type=int)
    pagination = cns_stock_industry.query.join(cns_sub_industry).add_columns(cns_sub_industry.industry_gics_4).join(
        cns_industry).add_columns(cns_industry.industry_gics_3).join(cns_group_industry).add_columns(
        cns_group_industry.industry_gics_2).join(cns_department_industry).add_columns(
        cns_department_industry.industry_gics_1).join(stock_grade_l).add_columns(func.max(stock_grade_l.the_year),
                                                                                 stock_grade_l.investment_id).join(
        invest_grade).add_columns(invest_grade.investment_name).group_by(
        cns_stock_industry.trade_code).paginate(page, per_page=200, error_out=False)
    # 说明：共有3197条记录 此为分页功能 # 改成了3185个记录
    result = pagination.items
    length = len(result)
    return render_template("global_industry/cns_market.html", result=result, length=length, trade_code=trade_code,
                           rs=rs, data_len=data_len)


# ----美国市场----
@globalindustry_blueprint.route('/usa_market', methods=('GET', 'POST'))
@globalindustry_blueprint.route('/usa_market/<string:query_history>/<string:trade_code>/<string:sec_name>',
                                methods=('GET', 'POST'))
def usa_market(sec_name=None, trade_code=None, query_history=None):
    sec_name = sec_name
    trade_code = trade_code
    query_history = query_history
    form = invest_updateForm()
    # 终于调试成功了！！！
    page = request.args.get('page', 1, type=int)
    pagination = usa_stock_industry.query.join(usa_sub_industry).add_columns(usa_sub_industry.industry_gics_4).join(
        usa_industry).add_columns(usa_industry.industry_gics_3).join(usa_group_industry).add_columns(
        usa_group_industry.industry_gics_2).join(usa_department_industry).add_columns(
        usa_department_industry.industry_gics_1).join(usa_stock_grade_l).add_columns(usa_stock_grade_l.grade_time).join(
        invest_grade).add_columns(invest_grade.grade_name).order_by(usa_stock_industry.trade_code).paginate(page,
                                                                                                            per_page=200,
                                                                                                            error_out=False)
    # 说明：共有3197条记录 此为分页功能 # 改成了3185个记录
    result = pagination.items
    length = len(result)
    history_data = None
    history_data_len = None
    if query_history == 'yes':
        history_data = stock_grade_h.query.filter_by(trade_code=trade_code).order_by(
            stock_grade_h.grade_time.desc()).join(invest_grade).add_columns(invest_grade.grade_name).all()
        history_data_len = len(history_data)
        sec_name = None
    return render_template("global_industry/usa/usa_market.html", form=form, sec_name=sec_name, trade_code=trade_code,
                           query_history=query_history, result=result, pagination=pagination, length=length,
                           history_data=history_data, history_data_len=history_data_len)


@globalindustry_blueprint.route('/cns_market_new', methods=('GET', 'POST'))
@login_required
def cns_market_new():
    return render_template("global_industry/cns_market_new.html")

@globalindustry_blueprint.route('/hks_market', methods=('GET', 'POST'))
@login_required
def hks_market():
    return render_template("global_industry/hks_market.html")



@globalindustry_blueprint.route('/uks_market', methods=('GET', 'POST'))
@login_required
def uks_market():
    return render_template("global_industry/uks_market.html")


@globalindustry_blueprint.route('/eps_market', methods=('GET', 'POST'))
@login_required
def eps_market():
    return render_template("global_industry/eps_market.html")


@globalindustry_blueprint.route('/jps_market', methods=('GET', 'POST'))
@login_required
def jps_market():
    return render_template("global_industry/jps_market.html")

@globalindustry_blueprint.route('/usa_market_new', methods=('GET', 'POST'))
@login_required
def usa_market_new():
    return render_template("global_industry/usa_market.html")

webapp/controllers/main.py
# coding=utf-8
import os
from flask import Blueprint, redirect, url_for, flash, render_template, current_app, request, jsonify
from webapp.forms import LoginForm, RegisterForm
from webapp.models import users, db, Permission
from flask_login import login_user, login_required, logout_user, current_user
from flask_principal import Identity, AnonymousIdentity, identity_changed
from webapp.decorators import admin_required, permission_required
from webapp.models import *
from webapp.sms import *
import random

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)

Verification_code_list = {}


# 登录界面
@main_blueprint.route('/')
def index():
    return redirect(url_for('main.login'))


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    register_form = RegisterForm()
    if form.validate_on_submit():
        user = users.query.filter_by(username=form.username.data).one()
        login_user(user, remember=form.remember.data)
        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.username)
        )
        # phone = "13234045805"
        # text = "【253云通讯】您的验证码是1234"
        # send_sms(text, phone)
        flash("You have been logged in", category="success")
        return redirect(url_for('stock.home', usersname=user.username))
    return render_template('main/login.html', form=form, register_form=register_form)


@main_blueprint.route('/personal/', methods=['GET', 'POST'])
def personal():
    user = users_roles.query.filter_by(user_name=current_user.username).first()
    # rolename = Role.query.filter_by(id=user.permissions).first()
    role = Role.query.filter_by(id=user.permissions).first()
    rolename = role.description
    return render_template('personal/person.html', user=user, rolename=rolename)


@main_blueprint.route('/myposition/', methods=['GET', 'POST'])
@login_required
def analysis():
    return render_template('personal/analysis.html', current_user=current_user)


# 手机注册
@main_blueprint.route('/register_phone', methods=['GET', 'POST'])
def register_phone():
    phone_number = request.args.get('phone_number')
    password = request.args.get('password')
    confirm_password = request.args.get('confirm_password')
    Verification_code = request.args.get('Verification_code')
    data = {}

    if Verification_code_list[phone_number] == Verification_code:
        new_user = users()
        new_user.username = phone_number
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        new_user_role = users_roles()
        new_user_role.user_name = phone_number
        new_user_role.permissions = 3
        db.session.add(new_user_role)
        db.session.commit()
        data['msg'] = 'success'
        return jsonify(data)
    data['msg'] = 'failure'
    return jsonify(data)


# 发送验证码短信
@main_blueprint.route('/send_Verification_code', methods=['GET', 'POST'])
def send_Verification_code():
    phone_number = request.args.get('phone_number')
    data = {}
    # 判断是否已经注册
    result = users.query.filter_by(username=phone_number).first()
    if result:
        data['exit'] = 'true'
        data['aaa'] = result.username
        return jsonify(data)
    else:
        data['exit'] = 'flase'
        Verification_code = str(random.randint(100000, 999999))
        Verification_code_list[phone_number] = Verification_code
        text = '【中勋科技】您的验证码是' + Verification_code
        send_sms(text, phone_number)
        data['phone_number'] = phone_number
        data['Verification_code'] = Verification_code

        return jsonify(data)


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        new_user = users()
        new_user.username = register_form.username.data
        new_user.set_password(register_form.password.data)
        db.session.add(new_user)
        db.session.commit()

        new_user_role = users_roles()
        new_user_role.user_name = register_form.username.data
        new_user_role.permissions = 3
        db.session.add(new_user_role)
        db.session.commit()

        flash(
            "注册成功！请登录",
            category="success"
        )
        return redirect(url_for('.login'))
    else:
        return redirect(url_for('.login'))


@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    identity_changed.send(
        current_app._get_current_object(),
        identity=AnonymousIdentity()
    )
    return redirect(url_for('main.login'))


@main_blueprint.route('/test')
def test():
    return render_template('test.html')


@main_blueprint.route('/my_favoritecode/', methods=['GET', 'POST'])
def my_favoritecode():
    user = users_roles.query.filter_by(user_name=current_user.username).first()
    # rolename = Role.query.filter_by(id=user.permissions).first()
    role = Role.query.filter_by(id=user.permissions).first()
    rolename = role.description
    return render_template('personal/my_favoritecode.html', user=user, rolename=rolename)


@main_blueprint.route('/admin/', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.administrator)
def admin():
    user = users_roles.query.filter_by(user_name=current_user.username).first()
    # rolename = Role.query.filter_by(id=user.permissions).first()
    role = Role.query.filter_by(id=user.permissions).first()
    rolename = role.description
    return render_template('admin/admin_permission.html', user=user, rolename=rolename)




# # 登录界面
# @main_blueprint.route('/oldpage')
# def index():
#     return redirect(url_for('main.login'))


# @main_blueprint.route('/login', methods=['GET', 'POST'])
# def login():
#     form = LoginForm()
#     register_form = RegisterForm()
#     if form.validate_on_submit():
#         user = users.query.filter_by(username=form.username.data).one()
#         login_user(user, remember=form.remember.data)
#         identity_changed.send(
#             current_app._get_current_object(),
#             identity=Identity(user.username)
#         )
#         # phone = "13234045805"
#         # text = "【253云通讯】您的验证码是1234"
#         # send_sms(text, phone)
#         flash("You have been logged in", category="success")
#         return redirect(url_for('stock.home',usersname=user.username))
#     return render_template('main/login.html', form=form, register_form=register_form)









# @main_blueprint.route('/register', methods=['GET', 'POST'])
# def register():
#     register_form = RegisterForm()
#     if register_form.validate_on_submit():
#         new_user = users()
#         new_user.username = register_form.username.data
#         new_user.set_password(register_form.password.data)
#         db.session.add(new_user)
#         db.session.commit()
#
#         new_user_role = users_roles()
#         new_user_role.user_name = register_form.username.data
#         new_user_role.permissions = 3
#         db.session.add(new_user_role)
#         db.session.commit()
#
#         flash(
#             "注册成功！请登录",
#             category="success"
#         )
#         return redirect(url_for('.login'))
#     else:
#         return redirect(url_for('.login'))

webapp/templates/stock_base_visitor.html
<html>
<head>
    <meta charset='utf-8'>

    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery-2.0.0.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery-ui') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/echarts.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/china.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.pagination.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static',filename="DataTables-1.10.15/media/js/jquery.dataTables.js") }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static',filename='DataTables-1.10.15/fixedcolumns/js/dataTables.fixedColumns.js') }}"></script>
    {#excel#}
    {#dataTables.bootstrap.min.js#}
    <script type="text/javascript"
            src="{{ url_for('static',filename='DataTables-1.10.15/dataTables.bootstrap.min.js') }}"></script>
    {#dataTables.responsive.min.js#}
    <script type="text/javascript"
            src="{{ url_for('static',filename='DataTables-1.10.15/extensions/Responsive/js/dataTables.responsive.min.js') }}"></script>
    {#dataTables.buttons.min.js#}
    <script type="text/javascript"
            src="{{ url_for('static',filename='DataTables-1.10.15/extensions/Buttons/js/dataTables.buttons.min.js') }}"></script>
    {#jszip.min.js#}
    <script type="text/javascript"
            src="{{ url_for('static',filename='DataTables-1.10.15/JSZip-2.5.0/jszip.min.js') }}"></script>
    {#buttons.html5.min.js#}
    <script type="text/javascript"
            src="{{ url_for('static',filename='DataTables-1.10.15/extensions/Buttons/js/buttons.html5.min.js') }}"></script>
    {#end excel#}
    <script type="text/javascript" src="{{ url_for('static',filename='icheck/icheck.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static',filename='bootstrap_datetimepicker/js/bootstrap-datetimepicker.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static',filename='bootstrap_select/js/bootstrap-select.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap-suggest.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.cookie.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/nav.js') }}"></script>
    {#    生成树插件#}
    <script type="text/javascript" src="{{ url_for('static',filename='js/dtree.js') }}"></script>

    <link href="{{ url_for('static',filename='bootstrap_select/css/bootstrap-select.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='css/pagination.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='bootstrap_datetimepicker/css/bootstrap-datetimepicker.css') }}"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='icheck/skins/minimal/blue.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="http://jqueryui.com/resources/demos/style.css">
    <link href="{{ url_for('static',filename='DataTables-1.10.15/media/css/jquery.dataTables.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='DataTables-1.10.15/fixedcolumns/css/fixedColumns.dataTables.css') }}"
          rel="stylesheet" type="text/css">
    <!--链接本地文件的写法，css和js的写法不一样 ps:还有一个js文件在上面-->
    <link href="{{ url_for('static',filename='css/loader.min.css') }}"
          rel="stylesheet" type="text/css">

    {#    library for new  templates#}
    <link href="{{ url_for('static',filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" media="screen">
    {#    <link href="{{ url_for('static',filename='bootstrap/css/bootstrap-responsive.min.css') }}" rel="stylesheet"#}
    {#          media="screen">#}
    <link href="{{ url_for('static',filename='css/nav.css') }}" rel="stylesheet" media="screen">
    <link type="text/css" href="{{ url_for('static',filename='css/theme.css') }}" rel="stylesheet">
    <link type="text/css" href="{{ url_for('static',filename='images/icons/css/font-awesome.css') }}" rel="stylesheet">
    <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
          rel='stylesheet'>
    <link type="text/css" href="{{ url_for('static',filename='css/dtree.css') }}" rel="stylesheet">
    <!--自动补全-->

    <script>
        $(function () {
            var availableTags =
                [{% for x in list_len %} <!--这里直接写range(list_len)不行，会在返回功能主页时出错"list_len is undefined"-->
                    {% for i in (0,1) %}
                        "{{ rs[x][i] }}",
                    {% endfor %}
                {% endfor %}];
            $("#tags").autocomplete({
                source: availableTags
            });
        });
    </script>
    <!--锁定行列的js文件-->
    <script type="text/javascript" src="{{ url_for('static',filename='js/tableHeadFixer.js') }}"></script>
    <!--js的分页方法，用于industry_analysis/annual_table.html-->
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.pagination.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/china.js') }}"></script>
    <style>
        * {
            font-family: "Times New Roman";
            font-size: 12px;
        }

        .td_num {
            text-align: right;
            border-style: none;
        }

        .td_num_2 {
            text-align: left;
            border-style: none;
        }

        .td_project {
            text-align: left;
            border-left-style: none;
            border-top-style: none;
            border-bottom-style: none;
        }

        .td_bottom_line {
            text-align: right;
            border-left-style: none;
            border-top-style: none;
            border-right-style: none;
        }

        .td_bottom_line_title {
            text-align: left;
            border-left-style: none;
            border-top-style: none;
            border-right-style: none;
        }

        .td_bottom_line_title_2 {
            text-align: left;
            border-left-style: none;
            border-top-style: none;
        }

        {# 这行有什么用 #}
        .leftbox {
            width: 15%;
            height: 100%;
            float: left;

        }

        .rightbox {
            width: 85%;
            height: 100%;
            float: left;

        }

        #temptable {
            table-layout: inherit;
            width: 100px;
        }

        #zyqnav ul ul {
            display: none;
            position: absolute;
            left: 100%;
            top: 0;
            background-color: white;
            border: 1px solid lightgrey;
        }

        #zyqnav ul li:hover > ul { /* > 子菜单选择器 鼠标在li上的时候 改变子ul的display属性*/
            display: block;
        }
    </style>
    {% block styles %}{% endblock %}
</head>
<body>
<div class="navbar navbar-fixed-top" style="position: fixed;top: 0">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <i class="icon-reorder shaded"></i></a>
            <a class="brand" href="{{ url_for("stock.home") }}">Fin-magic 魔法金融 </a>
            <div class="nav-collapse collapse navbar-inverse-collapse">
                {% block searchForm %}{% endblock %}
                <ul class="nav pull-right" id="onav">
                    <li><a href="{{ url_for('main.index') }}"><i class="icon-th-list"></i>登陆账户</a></li>
                    <li><a href="{{ url_for('stock.home') }}"><i class="icon-home"></i>返回主页</a></li>
                    <li><a href="#"><img id="myavatar" src="../static/avatar/user.png" class="nav-avatar"/></a></li>
                    <li style="padding: 8px"><button class="btn btn-primary" onclick="window.location.href='{{ url_for("main.index") }}'">登陆</button></li>
                </ul>
            </div>
            <!-- /.nav-collapse -->
        </div>
    </div>
    <!-- /navbar-inner -->
</div>

<div class="wrapper" id="container">
    <div class="container">
        <div class="row" style="height: auto">
            <div class="span3" style="height: auto"></div>
            <div class="span3" style="position: fixed;top: auto">

                <div class="sidebar">
                    <ul class="widget widget-menu unstyled">
                        <li class="active"><a href="{{ url_for('main.index') }}"><i
                                class="menu-icon icon-dashboard"></i>登陆我的账户
                        </a></li>
                    </ul>
                    <!--/.widget-nav-->
                    <ul class="widget widget-menu unstyled">
                        <li><a class="collapsed" data-toggle="collapse" href="#togglePages" aria-expanded="true"><i
                                class="menu-icon icon-cog">
                        </i><i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right">
                        </i>财务分析 </a>
                            <ul id="togglePages" class="collapse unstyled">
                                <li><a href="{{ url_for('stock_solo.basic') }}"><i class="icon-inbox"></i>股票个体分析 </a>
                                </li>
                                <li><a href="{{ url_for('stock_group.navigation') }}"><i class="icon-inbox"></i>股票总体概览
                                </a></li>
                                <li><a href="{{ url_for('industry_analysis.mymark') }}"><i class="icon-inbox"></i>整体行业状况分析
                                </a></li>
                                <li><a href="{{ url_for('global_industry.basic') }}"><i class="icon-inbox"></i>投资分类评级
                                </a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--/.sidebar-->
            </div>
            <!--/.span3-->
            {% block body %}{% endblock %}
            <!--/.span9-->
        </div>
        {% block bottombody %}{% endblock %}
    </div>
    <!--/.container-->
</div>
</body>
<script>
    $(document).ready(function () {
        var navheight = $("div.navbar").height();
        $("#container").css("margin-top", navheight);
    })
    setInterval(aa, 300000);
    setInterval(bb, 300000);

    function aa() {
        $.ajax({
            type: 'GET',
            url: '{{ url_for("message_api.get_message_count") }}',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                if (data.count > 0) {
                    $("#personal_message_count").text(data.count)
                }
                else {
                    $("#personal_message_count").text('暂无未读')
                }

            }
        })
    }

    function bb() {
        $.ajax({
            type: 'GET',
            url: '{{ url_for("message_api.get_system_message_count") }}',
            dataType: 'json',
            success: function (data) {
                if (data.count > 0) {
                    $("#system_message_count").text(data.count)
                }
                else {
                    $("#system_message_count").text('暂无未读')
                }

            }
        })
    }

</script>
{% block JavaScripts %}{% endblock %}
</html>